# Generated by Django 5.2 on 2025-04-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('director', 'Director'), ('salesassociate', 'Sales Associate'), ('salesprofessional', 'Sales Professional')], default='salesassociate', max_length=20),
        ),
    ]
