# Generated by Django 5.2 on 2025-04-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_property_bathrooms_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email')], default='email', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(choices=[('selling', "I'm thinking of selling"), ('buying', "I'm thinking of buying"), ('career', 'Career Opportunities'), ('support', 'Customer Support')], default='support', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email')], default='email', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
